// <auto-generated />
using System;
using ApprovalWorkflow.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Application.Infrastructure.ApprovalWorkflow.Persistence.Migrations
{
    [DbContext(typeof(ApprovalWorkflowDbContext))]
    partial class ApprovalWorkflowDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Domain.ApprovalWorkflow.Applications.ApprovalApplication", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ApplicantId")
                        .HasColumnType("uuid")
                        .HasColumnName("ApplicantId");

                    b.Property<DateTime?>("ApprovedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ApprovedAt");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("Content");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("CreatedAt");

                    b.Property<int>("CurrentStepNumber")
                        .HasColumnType("integer")
                        .HasColumnName("CurrentStepNumber");

                    b.Property<DateTime?>("RejectedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("RejectedAt");

                    b.Property<DateTime?>("ReturnedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ReturnedAt");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("Status");

                    b.Property<DateTime?>("SubmittedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("SubmittedAt");

                    b.Property<int>("Type")
                        .HasColumnType("integer")
                        .HasColumnName("Type");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("UpdatedAt");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("Version");

                    b.Property<Guid?>("WorkflowDefinitionId")
                        .HasColumnType("uuid")
                        .HasColumnName("WorkflowDefinitionId");

                    b.HasKey("Id");

                    b.HasIndex("ApplicantId")
                        .HasDatabaseName("IX_aw_Applications_ApplicantId");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("IX_aw_Applications_CreatedAt");

                    b.HasIndex("Status")
                        .HasDatabaseName("IX_aw_Applications_Status");

                    b.HasIndex("Type")
                        .HasDatabaseName("IX_aw_Applications_Type");

                    b.HasIndex("WorkflowDefinitionId")
                        .HasDatabaseName("IX_aw_Applications_WorkflowDefinitionId");

                    b.ToTable("aw_Applications", (string)null);
                });

            modelBuilder.Entity("Domain.ApprovalWorkflow.WorkflowDefinitions.WorkflowDefinition", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("ApplicationType")
                        .HasColumnType("integer")
                        .HasColumnName("ApplicationType");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("CreatedAt");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("Description");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("IsActive");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("Name");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("UpdatedAt");

                    b.Property<long>("Version")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationType")
                        .HasDatabaseName("IX_aw_WorkflowDefinitions_ApplicationType");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("IX_aw_WorkflowDefinitions_IsActive");

                    b.HasIndex("ApplicationType", "IsActive")
                        .IsUnique()
                        .HasDatabaseName("IX_aw_WorkflowDefinitions_ApplicationType_Active")
                        .HasFilter("[IsActive] = 1");

                    b.ToTable("aw_WorkflowDefinitions", (string)null);
                });

            modelBuilder.Entity("Shared.Domain.Outbox.OutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Error")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<DateTime>("OccurredOnUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("ProcessedOnUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("RetryCount")
                        .HasColumnType("integer");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.HasKey("Id");

                    b.HasIndex("ProcessedOnUtc")
                        .HasDatabaseName("IX_aw_OutboxMessages_ProcessedOnUtc");

                    b.ToTable("aw_OutboxMessages", (string)null);
                });

            modelBuilder.Entity("Domain.ApprovalWorkflow.Applications.ApprovalApplication", b =>
                {
                    b.OwnsMany("Domain.ApprovalWorkflow.Applications.ApprovalHistoryEntry", "ApprovalHistory", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("uuid");

                            b1.Property<int>("Action")
                                .HasColumnType("integer")
                                .HasColumnName("Action");

                            b1.Property<Guid>("ApplicationId")
                                .HasColumnType("uuid");

                            b1.Property<Guid>("ApproverId")
                                .HasColumnType("uuid")
                                .HasColumnName("ApproverId");

                            b1.Property<string>("Comment")
                                .HasMaxLength(2000)
                                .HasColumnType("character varying(2000)")
                                .HasColumnName("Comment");

                            b1.Property<int>("StepNumber")
                                .HasColumnType("integer")
                                .HasColumnName("StepNumber");

                            b1.Property<DateTime>("Timestamp")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("Timestamp");

                            b1.HasKey("Id");

                            b1.HasIndex("ApplicationId");

                            b1.ToTable("aw_ApprovalHistory", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("ApplicationId");
                        });

                    b.Navigation("ApprovalHistory");
                });

            modelBuilder.Entity("Domain.ApprovalWorkflow.WorkflowDefinitions.WorkflowDefinition", b =>
                {
                    b.OwnsMany("Domain.ApprovalWorkflow.WorkflowDefinitions.WorkflowStep", "Steps", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("uuid");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("Name");

                            b1.Property<string>("Role")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("Role");

                            b1.Property<int>("StepNumber")
                                .HasColumnType("integer")
                                .HasColumnName("StepNumber");

                            b1.Property<Guid>("WorkflowDefinitionId")
                                .HasColumnType("uuid");

                            b1.HasKey("Id");

                            b1.HasIndex("WorkflowDefinitionId", "StepNumber")
                                .IsUnique()
                                .HasDatabaseName("IX_aw_WorkflowSteps_DefinitionId_StepNumber");

                            b1.ToTable("aw_WorkflowSteps", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("WorkflowDefinitionId");
                        });

                    b.Navigation("Steps");
                });
#pragma warning restore 612, 618
        }
    }
}
