// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PurchaseManagement.Infrastructure.Persistence;

#nullable disable

namespace PurchaseManagement.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(PurchaseManagementDbContext))]
    [Migration("20251107201459_PurchaseManagement_InitialCreate")]
    partial class PurchaseManagement_InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("PurchaseManagement.Shared.Domain.PurchaseRequests.PurchaseRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("ApprovedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ApprovedAt");

                    b.Property<DateTime?>("CancelledAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("CancelledAt");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("CreatedAt");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("Description");

                    b.Property<DateTime?>("RejectedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("RejectedAt");

                    b.Property<Guid>("RequesterId")
                        .HasColumnType("uuid")
                        .HasColumnName("RequesterId");

                    b.Property<string>("RequesterName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("RequesterName");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("Status");

                    b.Property<DateTime?>("SubmittedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("SubmittedAt");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("Title");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("Version");

                    b.HasKey("Id");

                    b.ToTable("PurchaseRequests", (string)null);
                });

            modelBuilder.Entity("Shared.Domain.Outbox.OutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("Content");

                    b.Property<string>("Error")
                        .HasColumnType("text")
                        .HasColumnName("Error");

                    b.Property<DateTime>("OccurredOnUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("OccurredOnUtc");

                    b.Property<DateTime?>("ProcessedOnUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ProcessedOnUtc");

                    b.Property<int>("RetryCount")
                        .HasColumnType("integer")
                        .HasColumnName("RetryCount");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("Type");

                    b.HasKey("Id");

                    b.HasIndex("ProcessedOnUtc")
                        .HasDatabaseName("IX_pm_OutboxMessages_ProcessedOnUtc");

                    b.ToTable("pm_OutboxMessages", (string)null);
                });

            modelBuilder.Entity("PurchaseManagement.Shared.Domain.PurchaseRequests.PurchaseRequest", b =>
                {
                    b.OwnsMany("PurchaseManagement.Shared.Domain.PurchaseRequests.ApprovalStep", "ApprovalSteps", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("uuid");

                            b1.Property<DateTime?>("ApprovedAt")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("ApprovedAt");

                            b1.Property<Guid>("ApproverId")
                                .HasColumnType("uuid")
                                .HasColumnName("ApproverId");

                            b1.Property<string>("ApproverName")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("ApproverName");

                            b1.Property<string>("ApproverRole")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("ApproverRole");

                            b1.Property<string>("Comment")
                                .HasMaxLength(2000)
                                .HasColumnType("character varying(2000)")
                                .HasColumnName("Comment");

                            b1.Property<Guid>("PurchaseRequestId")
                                .HasColumnType("uuid");

                            b1.Property<DateTime?>("RejectedAt")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("RejectedAt");

                            b1.Property<int>("Status")
                                .HasColumnType("integer")
                                .HasColumnName("Status");

                            b1.Property<int>("StepNumber")
                                .HasColumnType("integer")
                                .HasColumnName("StepNumber");

                            b1.HasKey("Id");

                            b1.HasIndex("PurchaseRequestId");

                            b1.ToTable("ApprovalSteps", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("PurchaseRequestId");
                        });

                    b.OwnsMany("PurchaseManagement.Shared.Domain.PurchaseRequests.PurchaseRequestItem", "Items", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("uuid");

                            b1.Property<Guid>("ProductId")
                                .HasColumnType("uuid")
                                .HasColumnName("ProductId");

                            b1.Property<string>("ProductName")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("ProductName");

                            b1.Property<Guid>("PurchaseRequestId")
                                .HasColumnType("uuid");

                            b1.Property<int>("Quantity")
                                .HasColumnType("integer")
                                .HasColumnName("Quantity");

                            b1.HasKey("Id");

                            b1.HasIndex("PurchaseRequestId");

                            b1.ToTable("PurchaseRequestItems", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("PurchaseRequestId");

                            b1.OwnsOne("ProductCatalog.Shared.Domain.Products.Money", "Amount", b2 =>
                                {
                                    b2.Property<Guid>("PurchaseRequestItemId")
                                        .HasColumnType("uuid");

                                    b2.Property<decimal>("Amount")
                                        .HasPrecision(18, 2)
                                        .HasColumnType("numeric(18,2)")
                                        .HasColumnName("Amount");

                                    b2.Property<string>("Currency")
                                        .IsRequired()
                                        .ValueGeneratedOnUpdateSometimes()
                                        .HasMaxLength(3)
                                        .HasColumnType("character varying(3)")
                                        .HasColumnName("Currency");

                                    b2.HasKey("PurchaseRequestItemId");

                                    b2.ToTable("PurchaseRequestItems");

                                    b2.WithOwner()
                                        .HasForeignKey("PurchaseRequestItemId");
                                });

                            b1.OwnsOne("ProductCatalog.Shared.Domain.Products.Money", "UnitPrice", b2 =>
                                {
                                    b2.Property<Guid>("PurchaseRequestItemId")
                                        .HasColumnType("uuid");

                                    b2.Property<decimal>("Amount")
                                        .HasPrecision(18, 2)
                                        .HasColumnType("numeric(18,2)")
                                        .HasColumnName("UnitPrice");

                                    b2.Property<string>("Currency")
                                        .IsRequired()
                                        .ValueGeneratedOnUpdateSometimes()
                                        .HasMaxLength(3)
                                        .HasColumnType("character varying(3)")
                                        .HasColumnName("Currency");

                                    b2.HasKey("PurchaseRequestItemId");

                                    b2.ToTable("PurchaseRequestItems");

                                    b2.WithOwner()
                                        .HasForeignKey("PurchaseRequestItemId");
                                });

                            b1.Navigation("Amount")
                                .IsRequired();

                            b1.Navigation("UnitPrice")
                                .IsRequired();
                        });

                    b.OwnsOne("PurchaseManagement.Shared.Domain.PurchaseRequests.PurchaseRequestNumber", "RequestNumber", b1 =>
                        {
                            b1.Property<Guid>("PurchaseRequestId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)")
                                .HasColumnName("RequestNumber");

                            b1.HasKey("PurchaseRequestId");

                            b1.ToTable("PurchaseRequests");

                            b1.WithOwner()
                                .HasForeignKey("PurchaseRequestId");
                        });

                    b.Navigation("ApprovalSteps");

                    b.Navigation("Items");

                    b.Navigation("RequestNumber")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
